### ISSUE TITLE
[meta] Add GSP consumer

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVConsumer#13]
## Detailed Description
Add config file for GSPs

Should be able to use the same framework, to pull all the gsp data

Need to think how to pull data from yesterday, as the GSP results are updated roughly around midnight

- [ ] load GSP data
- [ ] add infrastructure terraform and deploy to AWS
- [ ] add datamodel GSP yields

**Comment by peterdudfield** [comment]
Thought was to add this to the same database server as PV data
