### ISSUE TITLE
[Meta] PV consumer

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVConsumer#2]
General issue for pv consumer to be built

- [x] make app to get pv data from uk and save to a database: https://github.com/openclimatefix/pvoutput/issues/90
- [x] fix tests: : https://github.com/openclimatefix/pvoutput/issues/91
- [x] codecov > 70%: openclimatefix/PVConsumer#3
- [x] update readme: openclimatefix/PVConsumer#4
- [x] uplaod docker file to dockerhub: openclimatefix/PVConsumer#5
- [x] https://github.com/openclimatefix/PVConsumer/issues/6

other repos:
- [x] datamodel from pv: https://github.com/openclimatefix/nowcasting_datamodel/issues/4
- [x] datamodel: read and write functions: https://github.com/openclimatefix/nowcasting_datamodel/issues/5
- [x] terraform database: https://github.com/openclimatefix/nowcasting_infrastructure/issues/38
- [x] terraform iam policies, for pv outpur.org key, and database secret:  https://github.com/openclimatefix/nowcasting_infrastructure/issues/39
- [x] terraform ecs: pv conusmer: https://github.com/openclimatefix/nowcasting_infrastructure/issues/40

**Comment by peterdudfield** [comment]
@JulianBriggs Im going to close this issue now. 

I think you have built your own tool, but I think this could be deployed fairly easy in a different country. Its default is set up on some systems in the UK. Let me know if you want any support on this
